# Generated by Django 4.2.7 on 2024-06-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default='Учень математики', max_length=150, verbose_name='rank'),
        ),
    ]
