# Generated by Django 4.2.7 on 2024-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileimage_remove_customuser_image_delete_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='mathlab/templates/static/profile_pics'),
        ),
    ]
