# Generated by Django 4.2.7 on 2024-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_score_rang_delete_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
