# Generated by Django 4.2.7 on 2024-04-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_score_id_alter_score_rang_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='score_id',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rang_id',
            new_name='rang',
        ),
    ]
