# Generated by Django 4.2.7 on 2024-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
