# Generated by Django 5.1.11 on 2025-08-18 13:29

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('theorist', '0013_theoristprofilesettings_permit_everyone_to_see_visit_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('GF', 'Graph Functions'),
                            ('MT', 'Matrices'),
                            ('RV', 'Equations'),
                            ('NR', 'Inequalities'),
                            ('SM', 'Systems of Equations'),
                            ('VM', 'Higher Mathematics'),
                            ('TY', 'Probability Theory'),
                            ('KM', 'Combinatorics'),
                            ('DM', 'Discrete Mathematics'),
                            ('PM', 'Elementary Mathematics'),
                            ('VD', 'Percentages'),
                            ('TG', 'Trigonometry'),
                            ('GM', 'Geometry'),
                            ('YS', 'Probability and Statistics'),
                            ('AL', 'Algorithms'),
                            ('AG', 'Algebra'),
                            ('IN', 'Other'),
                            ('MF', 'Math Facts'),
                        ],
                        max_length=2,
                        verbose_name='math quiz category',
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('ES', 'Easy'), ('NL', 'Normal'), ('HD', 'Hard'), ('EX', 'Extra Hard')],
                        default='NL',
                        max_length=2,
                        verbose_name='difficulty',
                    ),
                ),
                (
                    'finish_score_reward',
                    models.PositiveSmallIntegerField(default=15, verbose_name='score reward for quiz finishing'),
                ),
                ('average_solve_time_statistic', models.DurationField(blank=True, verbose_name='average solve time')),
                ('max_time_to_solve', models.TextField(blank=True, verbose_name='max time to solve')),
                ('math_expressions_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Math Quiz',
                'verbose_name_plural': 'Math Quizzes',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MathExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latex_expression', models.TextField()),
                ('max_time_to_solve', models.DurationField(verbose_name='max time to solve')),
                (
                    'score_reward',
                    models.PositiveSmallIntegerField(default=3, verbose_name='score reward for the single expression'),
                ),
                (
                    'math_quiz',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='math_expressions',
                        to='game_area.mathquiz',
                        verbose_name='Math Quiz',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Math Expression',
                'verbose_name_plural': 'Math Expressions',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MathQuizScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('solved_by_name_slug', models.SlugField(blank=True, max_length=255)),
                (
                    'most_popular_quiz_type',
                    models.CharField(
                        choices=[
                            ('GF', 'Graph Functions'),
                            ('MT', 'Matrices'),
                            ('RV', 'Equations'),
                            ('NR', 'Inequalities'),
                            ('SM', 'Systems of Equations'),
                            ('VM', 'Higher Mathematics'),
                            ('TY', 'Probability Theory'),
                            ('KM', 'Combinatorics'),
                            ('DM', 'Discrete Mathematics'),
                            ('PM', 'Elementary Mathematics'),
                            ('VD', 'Percentages'),
                            ('TG', 'Trigonometry'),
                            ('GM', 'Geometry'),
                            ('YS', 'Probability and Statistics'),
                            ('AL', 'Algorithms'),
                            ('AG', 'Algebra'),
                            ('IN', 'Other'),
                            ('MF', 'Math Facts'),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    'time_taken',
                    models.DurationField(
                        blank=True, null=True, verbose_name='time that was taken to solve all quizzes'
                    ),
                ),
                (
                    'board_score',
                    models.CharField(
                        choices=[
                            ('EM', 'Empty'),
                            ('BZ', 'Bronze'),
                            ('SI', 'Silver'),
                            ('GO', 'Gold'),
                            ('PL', 'Platinum'),
                        ],
                        default='EM',
                        max_length=2,
                    ),
                ),
                (
                    'solved_by',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'),
                ),
                ('solved_expressions', models.ManyToManyField(to='game_area.mathexpression')),
                ('solved_quizzes', models.ManyToManyField(to='game_area.mathquiz')),
            ],
            options={
                'verbose_name': 'Math Scoreboard',
                'verbose_name_plural': 'Math Scoreboards',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
