# Generated by Django 5.1.11 on 2025-08-26 10:38

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import dynamic_filenames
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('theorist', '0013_theoristprofilesettings_permit_everyone_to_see_visit_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latex_expression', models.TextField()),
                ('has_multiple_choices', models.BooleanField(default=False)),
                ('max_time_to_solve', models.DurationField(verbose_name='max time to solve')),
                (
                    'score_reward',
                    models.PositiveSmallIntegerField(default=3, verbose_name='score reward for the single expression'),
                ),
            ],
            options={
                'verbose_name': 'Math Expression',
                'verbose_name_plural': 'Math Expressions',
                'ordering': ('created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MathQuizChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('is_correct_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Math Quiz Choice Question',
                'verbose_name_plural': 'Math Quiz Choice Questions',
            },
        ),
        migrations.CreateModel(
            name='MathMultipleChoiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField()),
                (
                    'math_expression',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='multiple_choices_quizzes',
                        to='game_area.mathexpression',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Math Multiple Choice Task',
                'verbose_name_plural': 'Math Multiple Choice Task',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MathQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'math_description_image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='{app_label:.25}/quizzes/math_quiz/{instance.uuid}/image/{uuid:s}{ext}'
                        ),
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('GF', 'Graph Functions'),
                            ('MT', 'Matrices'),
                            ('RV', 'Equations'),
                            ('NR', 'Inequalities'),
                            ('SM', 'Systems of Equations'),
                            ('VM', 'Higher Mathematics'),
                            ('TY', 'Probability Theory'),
                            ('KM', 'Combinatorics'),
                            ('DM', 'Discrete Mathematics'),
                            ('PM', 'Elementary Mathematics'),
                            ('VD', 'Percentages'),
                            ('TG', 'Trigonometry'),
                            ('GM', 'Geometry'),
                            ('YS', 'Probability and Statistics'),
                            ('AL', 'Algorithms'),
                            ('AG', 'Algebra'),
                            ('IN', 'Other'),
                            ('MF', 'Math Facts'),
                        ],
                        max_length=2,
                        verbose_name='math quiz category',
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('ES', 'Easy'), ('NL', 'Normal'), ('HD', 'Hard'), ('EX', 'Extra Hard')],
                        default='NL',
                        max_length=2,
                        verbose_name='difficulty',
                    ),
                ),
                (
                    'finish_score_reward',
                    models.PositiveSmallIntegerField(default=15, verbose_name='score reward for quiz finishing'),
                ),
                ('author_name_slug', models.SlugField(blank=True, max_length=255)),
                (
                    'average_solve_time_statistic',
                    models.DurationField(blank=True, null=True, verbose_name='average solve time'),
                ),
                ('max_time_to_solve', models.DurationField(verbose_name='max time to solve')),
                ('math_expressions_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                (
                    'author',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Math Quiz',
                'verbose_name_plural': 'Math Quizzes',
                'ordering': ('created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='mathexpression',
            name='math_quiz',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='math_expressions',
                to='game_area.mathquiz',
                verbose_name='Math Quiz',
            ),
        ),
        migrations.CreateModel(
            name='MathMultipleChoiceTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='game_area.mathmultiplechoicetask'
                    ),
                ),
                (
                    'answer',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_area.mathquizchoiceanswer'),
                ),
            ],
            options={
                'unique_together': {('task', 'answer')},
            },
        ),
        migrations.AddField(
            model_name='mathmultiplechoicetask',
            name='answers',
            field=models.ManyToManyField(
                through='game_area.MathMultipleChoiceTaskAnswer', to='game_area.mathquizchoiceanswer'
            ),
        ),
        migrations.CreateModel(
            name='MathQuizScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('solved_by_name_slug', models.SlugField(blank=True, max_length=255)),
                (
                    'most_popular_quiz_type',
                    models.CharField(
                        choices=[
                            ('GF', 'Graph Functions'),
                            ('MT', 'Matrices'),
                            ('RV', 'Equations'),
                            ('NR', 'Inequalities'),
                            ('SM', 'Systems of Equations'),
                            ('VM', 'Higher Mathematics'),
                            ('TY', 'Probability Theory'),
                            ('KM', 'Combinatorics'),
                            ('DM', 'Discrete Mathematics'),
                            ('PM', 'Elementary Mathematics'),
                            ('VD', 'Percentages'),
                            ('TG', 'Trigonometry'),
                            ('GM', 'Geometry'),
                            ('YS', 'Probability and Statistics'),
                            ('AL', 'Algorithms'),
                            ('AG', 'Algebra'),
                            ('IN', 'Other'),
                            ('MF', 'Math Facts'),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    'time_taken_to_solve_quizzes',
                    models.DurationField(
                        blank=True, null=True, verbose_name='time that was taken to solve all quizzes'
                    ),
                ),
                (
                    'board_score',
                    models.CharField(
                        choices=[
                            ('EM', 'Empty'),
                            ('BZ', 'Bronze'),
                            ('SI', 'Silver'),
                            ('GO', 'Gold'),
                            ('PL', 'Platinum'),
                        ],
                        default='EM',
                        max_length=2,
                    ),
                ),
                (
                    'solved_by',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'
                    ),
                ),
                ('solved_expressions', models.ManyToManyField(blank=True, to='game_area.mathexpression')),
            ],
            options={
                'verbose_name': 'Math Scoreboard',
                'verbose_name_plural': 'Math Scoreboards',
                'ordering': ('created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MathSolvedQuizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'best_time_taken',
                    models.DurationField(blank=True, verbose_name='best time taken to finish this quiz'),
                ),
                ('math_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_area.mathquiz')),
                (
                    'math_quiz_scoreboard',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_area.mathquizscoreboard'),
                ),
            ],
            options={
                'verbose_name': 'Math solved quizzes',
                'unique_together': {('math_quiz', 'math_quiz_scoreboard')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='mathquizscoreboard',
            name='solved_quizzes',
            field=models.ManyToManyField(blank=True, through='game_area.MathSolvedQuizzes', to='game_area.mathquiz'),
        ),
    ]
