# Generated by Django 5.1.11 on 2025-08-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0001_initial'),
        ('theorist', '0013_theoristprofilesettings_permit_everyone_to_see_visit_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathexpression',
            options={
                'ordering': ('created_at',),
                'verbose_name': 'Math Expression',
                'verbose_name_plural': 'Math Expressions',
            },
        ),
        migrations.AlterModelOptions(
            name='mathquiz',
            options={'ordering': ('created_at',), 'verbose_name': 'Math Quiz', 'verbose_name_plural': 'Math Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='mathquizscoreboard',
            options={
                'ordering': ('created_at',),
                'verbose_name': 'Math Scoreboard',
                'verbose_name_plural': 'Math Scoreboards',
            },
        ),
        migrations.AlterModelOptions(
            name='mathsolvedquizzes',
            options={'verbose_name': 'Math solved quizzes'},
        ),
        migrations.RenameField(
            model_name='mathquizscoreboard',
            old_name='time_taken',
            new_name='time_taken_to_solve_quizzes',
        ),
        migrations.AddField(
            model_name='mathquiz',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'),
        ),
        migrations.AddField(
            model_name='mathquiz',
            name='author_name_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mathsolvedquizzes',
            name='best_time_taken',
            field=models.DurationField(blank=True, verbose_name='best time taken to finish this quiz'),
        ),
    ]
