# Generated by Django 5.1.11 on 2025-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathexpression',
            name='latex_correct_answer',
            field=models.TextField(blank=True),
        ),
    ]
