# Generated by Django 5.1.11 on 2025-08-27 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquiz',
            name='max_time_to_solve',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='max time to solve'),
        ),
        migrations.AlterField(
            model_name='mathsolvedquizzes',
            name='best_time_taken',
            field=models.DurationField(
                blank=True, default=datetime.timedelta(0), verbose_name='best time taken to finish this quiz'
            ),
        ),
    ]
