# Generated by Django 5.1.11 on 2025-08-26 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathmultiplechoicetaskanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='mathmultiplechoicetaskanswer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
