# Generated by Django 5.1.11 on 2025-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0002_mathmultiplechoicetaskanswer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathmultiplechoicetaskanswer',
            options={
                'verbose_name': 'Math Multiple Choice Task Answer',
                'verbose_name_plural': 'Math Multiple Choice Task Answers',
            },
        ),
        migrations.AlterField(
            model_name='mathquiz',
            name='max_time_to_solve',
            field=models.DurationField(blank=True, verbose_name='max time to solve'),
        ),
    ]
