# Generated by Django 5.1.11 on 2025-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0002_mathexpression_latex_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathsolvedexpressions',
            name='math_expression_answer',
            field=models.TextField(blank=True),
        ),
    ]
