# Generated by Django 5.1.11 on 2025-08-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0002_alter_mathexpression_options_alter_mathquiz_options_and_more'),
        ('theorist', '0013_theoristprofilesettings_permit_everyone_to_see_visit_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquiz',
            name='author',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'
            ),
        ),
        migrations.AlterField(
            model_name='mathquizscoreboard',
            name='solved_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theorist.theorist'
            ),
        ),
    ]
