# Generated by Django 5.1.11 on 2025-08-25 21:07

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0003_alter_mathquiz_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuizChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('is_correct_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Math Quiz Choice Question',
                'verbose_name_plural': 'Math Quiz Choice Questions',
            },
        ),
        migrations.AddField(
            model_name='mathexpression',
            name='has_multiple_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MathMultipleChoiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField()),
                (
                    'math_expression',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='multiple_choices_quizzes',
                        to='game_area.mathexpression',
                    ),
                ),
                ('answers', models.ManyToManyField(to='game_area.mathquizchoiceanswer')),
            ],
            options={
                'verbose_name': 'Math Multiple Choice Task',
                'verbose_name_plural': 'Math Multiple Choice Task',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
