# Generated by Django 5.1.11 on 2025-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0003_mathsolvedexpressions_math_expression_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquiz',
            name='min_expressions_to_successfully_finish',
            field=models.PositiveSmallIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='mathsolvedquizzes',
            name='is_successfully_finished',
            field=models.BooleanField(default=True),
        ),
    ]
