# Generated by Django 5.1.11 on 2025-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0003_alter_mathmultiplechoicetaskanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquiz',
            name='max_time_to_solve',
            field=models.DurationField(blank=True, default=0, verbose_name='max time to solve'),
        ),
    ]
