# Generated by Django 5.1.11 on 2025-08-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game_area', '0004_alter_mathquiz_max_time_to_solve'),
        ('theorist', '0013_theoristprofilesettings_permit_everyone_to_see_visit_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquizscoreboard',
            name='solved_by',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quiz_scoreboard',
                to='theorist.theorist',
            ),
        ),
    ]
