services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/mathlab
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - .env
    ports:
      - "5432:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    build: .
    restart: always
    command: celery -A server.settings.celery worker -l INFO
    depends_on:
      - web
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    restart: always
    command: celery -A server.settings.celery beat -l INFO
    depends_on:
      - web
      - redis
      - celery
    env_file:
      - .env

  flower:
    build:
      context: .
    command: celery -A server.settings.celery flower
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery-beat
      - celery
      - db

volumes:
  pgdata:
