services:
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: REDIS_RENDER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString