services:
  - type: worker
    name: celery-worker
    region: frankfurt
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A mathlab worker -l info"
    autoDeploy: false
    envVars:
      - key: REDIS_RENDER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: worker
    name: celery-beat
    region: frankfurt
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A mathlab worker --beat --scheduler django --loglevel=info"
    autoDeploy: false
    envVars:
      - key: REDIS_RENDER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: [ ]