# Generated by Django 5.1.6 on 2025-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorist',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theorist',
            name='onboarding_date',
            field=models.DateTimeField(null=True),
        ),
    ]
