# Generated by Django 5.1.6 on 2025-02-24 20:49

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0002_theorist_is_onboarded_theorist_onboarding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theorist',
            name='city',
        ),
        migrations.AddField(
            model_name='theorist',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
