# Generated by Django 5.1.6 on 2025-03-06 20:52

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


def generate_settings_for_theorists(apps, schema_editor):
    Theorist = apps.get_model('theorist', 'Theorist')
    TheoristProfileSettings = apps.get_model('theorist', 'TheoristProfileSettings')
    lst_to_add = []

    for theorist in Theorist.objects.all():
        lst_to_add.append(
            TheoristProfileSettings(
                theorist=theorist,
            )
        )
    TheoristProfileSettings.objects.bulk_create(lst_to_add)


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0003_remove_theorist_city_theorist_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoristProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_show_last_activities', models.BooleanField(default=True)),
                ('is_able_to_get_messages', models.BooleanField(default=True)),
                (
                    'theorist',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='theorist.theorist'
                    ),
                ),
            ],
            options={
                'verbose_name': 'theorist_profile_setting',
                'verbose_name_plural': 'theorist_profile_settings',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunPython(generate_settings_for_theorists, reverse_code=migrations.RunPython.noop),
    ]
