# Generated by Django 5.1.6 on 2025-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0016_commentsupport_postsupport'),
        ('theorist', '0003_remove_theorist_city_theorist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorist',
            name='comment_supports',
            field=models.ManyToManyField(
                related_name='supported_comments', through='forum.CommentSupport', to='theorist.theorist'
            ),
        ),
        migrations.AddField(
            model_name='theorist',
            name='post_supports',
            field=models.ManyToManyField(
                related_name='supported_posts', through='forum.PostSupport', to='theorist.theorist'
            ),
        ),
    ]
