# Generated by Django 5.1.7 on 2025-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0005_alter_theoristprofilesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristprofilesettings',
            name='is_profile_only_for_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theoristprofilesettings',
            name='is_show_about_me',
            field=models.BooleanField(default=True),
        ),
    ]
