# Generated by Django 5.1.7 on 2025-03-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0006_theoristprofilesettings_is_profile_only_for_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='theoristprofilesettings',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
