# Generated by Django 5.1.7 on 2025-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0007_alter_theorist_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='theoristprofilesettings',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
