# Generated by Django 5.1.9 on 2025-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0009_theoristfriendshipblacklist_theoristfriendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristprofilesettings',
            name='is_able_to_receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
