# Generated by Django 5.1.9 on 2025-05-18 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0010_theoristprofilesettings_is_able_to_receive_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorist',
            name='full_name',
            field=models.CharField(
                max_length=150, validators=[django.core.validators.MinLengthValidator(limit_value=6)]
            ),
        ),
    ]
