# Generated by Django 5.1.11 on 2025-06-13 15:28

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0011_alter_theorist_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorist',
            name='full_name',
            field=models.CharField(
                max_length=150,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(limit_value=6),
                ],
            ),
        ),
    ]
