# Generated by Django 5.1.11 on 2025-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist', '0012_alter_theorist_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristprofilesettings',
            name='permit_everyone_to_see_visit_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
