# Generated by Django 5.2 on 2025-04-06 14:50

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0002_alter_theoristchatgroupconfiguration_theorist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theoristmessage',
            name='message',
            field=django_bleach.models.BleachField(max_length=500),
        ),
    ]
