# Generated by Django 5.1.8 on 2025-04-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0003_alter_theoristmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristmessage',
            name='is_safe_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theoristmessage',
            name='was_safe_deleted_by',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_messages',
                to='theorist.theorist',
            ),
        ),
    ]
