# Generated by Django 5.1.11 on 2025-06-15 14:21

import django.db.models.deletion
from django.db import migrations, models


def mark_all_messages_as_read(apps, schema_editor):
    TheoristMessage = apps.get_model('theorist_chat', 'TheoristMessage')
    TheoristMessage.objects.update(is_read=True)


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0004_theoristmessage_is_message_safe_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theoristmessage',
            name='replied_to',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replies',
                to='theorist_chat.theoristmessage',
            ),
        ),
        migrations.RunPython(mark_all_messages_as_read, reverse_code=migrations.RunPython.noop),
    ]
