# Generated by Django 5.1.11 on 2025-06-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0005_theoristmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristmessage',
            name='replied_to',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replies',
                to='theorist_chat.theoristmessage',
            ),
        ),
    ]
