# Generated by Django 5.1.11 on 2025-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0005_theoristmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
