# Generated by Django 5.1.11 on 2025-07-20 14:47
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0007_theoristmessage_audio_message_and_more'),
    ]

    operations = [TrigramExtension()]
