# Generated by Django 5.1.11 on 2025-08-11 10:08

import django.core.validators
import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_chat', '0008_auto_20250720_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristmessage',
            name='media_message',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern='{app_label:.25}/rooms/{instance.room.uuid}/{instance.sender.full_name_slug}/media/{uuid:s}{ext}'
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4', 'mov'])
                ],
            ),
        ),
    ]
