# Generated by Django 5.1.7 on 2025-03-15 22:50

import django.contrib.postgres.fields
import django.utils.timezone
import server.apps.math_news.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('math_news', '0002_alter_mathnews_options_mathnews_background_colors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathnews',
            options={'get_latest_by': 'published_at', 'ordering': ('-published_at',), 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='mathnews',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='mathnews',
            name='new_url',
        ),
        migrations.RemoveField(
            model_name='mathnews',
            name='posted',
        ),
        migrations.AddField(
            model_name='mathnews',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mathnews',
            name='short_content',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mathnews',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='background_colors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=server.apps.math_news.models.default_background_colors,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
