# Generated by Django 5.1.7 on 2025-03-15 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('math_news', '0003_alter_mathnews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathnews',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='mathnews',
            old_name='url',
            new_name='origin_url',
        ),
    ]
