# Generated by Django 5.1.9 on 2025-05-26 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('math_news', '0005_alter_mathnews_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathnews',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name_plural': 'news'},
        ),
    ]
