# Generated by Django 5.0.10 on 2025-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_alter_post_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("GF", "Graph Functions"),
                            ("MT", "Matrices"),
                            ("RV", "Equations"),
                            ("NR", "Inequalities"),
                            ("SM", "Systems of Equations"),
                            ("VM", "Higher Mathematics"),
                            ("TY", "Probability Theory"),
                            ("KM", "Combinatorics"),
                            ("DM", "Discrete Mathematics"),
                            ("PM", "Elementary Mathematics"),
                            ("VD", "Percentages"),
                            ("TG", "Trigonometry"),
                            ("GM", "Geometry"),
                            ("YS", "Probability and Statistics"),
                            ("AL", "Algorithms"),
                            ("AG", "Algebra"),
                            ("IN", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="forum.postcategory"),
        ),
    ]
