# Generated by Django 5.0.10 on 2025-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0005_postcategory_remove_post_categories_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=85),
        ),
    ]
