# Generated by Django 5.0.10 on 2025-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0009_auto_20250212_2348"),
    ]

    operations = []
