# Generated by Django 5.0.10 on 2025-02-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0013_alter_post_options_commentdislike_and_more'),
        ('theorist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comments',
                to='theorist.theorist',
            ),
        ),
        migrations.AddField(
            model_name='commentdislike',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='theorist.theorist',
            ),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='theorist.theorist',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='theorist.theorist',
            ),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='theorist.theorist',
            ),
        ),
        migrations.AddField(
            model_name='postlike',
            name='theorist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='theorist.theorist',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(
                related_name='comment_dislikes',
                through='forum.CommentDislike',
                to='theorist.theorist',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(
                related_name='comment_likes',
                through='forum.CommentLike',
                to='theorist.theorist',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(
                related_name='post_dislikes',
                through='forum.PostDislike',
                to='theorist.theorist',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(
                related_name='post_likes',
                through='forum.PostLike',
                to='theorist.theorist',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='commentdislike',
            unique_together={('theorist', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('theorist', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postdislike',
            unique_together={('theorist', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('theorist', 'post')},
        ),
        migrations.RemoveField(
            model_name='commentdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
