# Generated by Django 5.1.6 on 2025-02-25 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0015_alter_comment_dislikes_alter_comment_likes_and_more'),
        ('theorist', '0003_remove_theorist_city_theorist_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.comment')),
                (
                    'theorist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comment_supports_relation',
                        to='theorist.theorist',
                    ),
                ),
            ],
            options={
                'unique_together': {('theorist', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='PostSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
                (
                    'theorist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='post_supports_relation',
                        to='theorist.theorist',
                    ),
                ),
            ],
            options={
                'unique_together': {('theorist', 'post')},
            },
        ),
    ]
