# Generated by Django 5.1.6 on 2025-02-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0016_commentsupport_postsupport'),
        ('theorist', '0003_remove_theorist_city_theorist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='supports',
            field=models.ManyToManyField(
                related_name='supported_comments', through='forum.CommentSupport', to='theorist.theorist'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='supports',
            field=models.ManyToManyField(
                related_name='supported_posts', through='forum.PostSupport', to='theorist.theorist'
            ),
        ),
        migrations.AlterField(
            model_name='commentsupport',
            name='theorist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theorist.theorist'),
        ),
        migrations.AlterField(
            model_name='postsupport',
            name='theorist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theorist.theorist'),
        ),
    ]
