# Generated by Django 5.1.9 on 2025-05-24 20:17
from itertools import chain

from django.db import migrations, models


def generate_unique_denormilized_theorist_names(apps, schema_editor):
    Post = apps.get_model('forum', 'Post')
    Comment = apps.get_model('forum', 'Comment')

    posts = Post.objects.filter(theorist__isnull=False)
    comments = Comment.objects.filter(theorist__isnull=False)

    for obj in chain(posts, comments):
        obj.theorist_full_name = obj.theorist.full_name
        obj.save(update_fields=['theorist_full_name'])


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0020_alter_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theorist_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='theorist_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(generate_unique_denormilized_theorist_names, reverse_code=migrations.RunPython.noop),
    ]
