# Generated by Django 5.1.9 on 2025-06-02 13:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0021_post_theorist_full_name'),
        ('theorist', '0011_alter_theorist_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text_body', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                (
                    'theorist',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='comment_answers',
                        to='theorist.theorist',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Comment Answer',
                'verbose_name_plural': 'Comment Answers',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='answers',
            field=models.ManyToManyField(blank=True, to='forum.commentanswer'),
        ),
    ]
