# Generated by Django 5.1.9 on 2025-05-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('theorist_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoristnotification',
            name='actor_display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theoristnotification',
            name='target_display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theoristnotification',
            name='theorist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to='theorist.theorist',
            ),
        ),
    ]
