# Generated by Django 4.2.7 on 2024-06-11 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dislikes',
            field=models.ManyToManyField(db_index=True, related_name='disliked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(db_index=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at', 'modified_at', 'post_views'], name='forum_post_created_9298c7_idx'),
        ),
    ]
