# Generated by Django 4.2.7 on 2024-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_post_dislikes_alter_post_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='forum_post_created_9298c7_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at',], name='forum_post_created_203958_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['modified_at'], name='forum_post_modified_02ef33_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_views'], name='forum_post_post_vi_6d1b3b_idx'),
        ),
    ]
