# Generated by Django 4.2.7 on 2024-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_modified_at_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
