# Generated by Django 4.2.7 on 2024-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_options_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
