# Generated by Django 4.2.7 on 2024-04-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'ordering': ('title',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
