# Generated by Django 4.2.7 on 2024-06-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_forum_post_created_9298c7_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='forum_post_created_d558d2_idx',
            old_name='forum_post_created_203958_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='forum_post_modifie_02ef33_idx',
            old_name='forum_post_modified_02ef33_idx',
        ),
    ]
