# Generated by Django 4.2.7 on 2024-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_forum_post_created_203958_idx_forum_post_created_d558d2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(db_index=True, related_name='post_categories', to='forum.category'),
        ),
    ]
