# Generated by Django 5.1.7 on 2025-03-22 21:55

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import dynamic_filenames
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('theorist', '0007_alter_theorist_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoristDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=95, null=True)),
                (
                    'draft',
                    models.ImageField(
                        max_length=300,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='{app_label:.25}/{instance.theorist.full_name_slug}/drafts/{uuid:s}{ext}'
                        ),
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public_available', models.BooleanField(default=False)),
                (
                    'theorist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='theorist.theorist'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
