# Generated by Django 5.1.7 on 2025-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drafts', '0002_alter_theoristdrafts_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theoristdrafts',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Theorist Draft',
                'verbose_name_plural': 'Theorist Drafts',
            },
        ),
        migrations.AlterField(
            model_name='theoristdrafts',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
