# Generated by Django 5.1.7 on 2025-03-25 22:26

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


def generate_nested_theorist_configurations(apps, schema_editor):
    Theorist = apps.get_model('theorist', 'Theorist')
    TheoristDraftsConfiguration = apps.get_model('drafts', 'TheoristDraftsConfiguration')
    to_create = []

    for theorist in Theorist.objects.all():
        to_create.append(TheoristDraftsConfiguration(theorist=theorist))
    TheoristDraftsConfiguration.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('drafts', '0003_alter_theoristdrafts_options_and_more'),
        ('theorist', '0007_alter_theorist_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoristDraftsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public_available', models.BooleanField(default=True)),
                (
                    'theorist',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='drafts_configuration',
                        to='theorist.theorist',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Theorist Draft Configuration',
                'verbose_name_plural': 'Theorist Drafts Configurations',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunPython(generate_nested_theorist_configurations, reverse_code=migrations.RunPython.noop),
    ]
