# Generated by Django 4.2.7 on 2024-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'sender'], name='chat_messag_receive_71134e_idx'),
        ),
    ]
