from typing import Final

BORINGAVATARS_DEFAULT_SIZE_QUALITY: Final[int] = 160
BORINGAVATARS_DEFAULT_SIZE_QUALITY_LIST: Final[list[int]] = [
    BORINGAVATARS_DEFAULT_SIZE_QUALITY,
    BORINGAVATARS_DEFAULT_SIZE_QUALITY,
]
BORINGAVATARS_DEFAULT_CROP: Final[str] = 'center'

BORINGAVATARS_DEFAULT_COLORS = ['#2f1335', '#620e5d', '#9d007a', '#ce3762', '#ff6e49']
