# Generated by Django 4.2.7 on 2024-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('new_url', models.CharField(max_length=255)),
                ('posted', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'math_news',
                'ordering': ('title',),
                'get_latest_by': 'posted_at',
            },
        ),
    ]
