# Generated by Django 4.2.7 on 2024-05-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mathnews',
            table=None,
        ),
    ]
