# Generated by Django 4.2.7 on 2024-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_news', '0002_alter_mathnews_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathnews',
            name='new_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
