# Generated by Django 4.2.7 on 2024-05-05 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('math_news', '0004_mathnews_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathnews',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
