# Generated by Django 4.2.7 on 2024-05-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_news', '0005_mathnews_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathnews',
            options={'get_latest_by': 'published_at', 'ordering': ('title',), 'verbose_name_plural': 'news'},
        ),
    ]
