# Generated by Django 5.1.7 on 2025-03-27 23:48

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import dynamic_filenames
import uuid
from django.db import migrations, models


def generate_nested_theorist_configurations(apps, schema_editor):
    Theorist = apps.get_model('theorist', 'Theorist')
    TheoristDraftsConfiguration = apps.get_model('theorist_drafts', 'TheoristDraftsConfiguration')
    to_create = []

    for theorist in Theorist.objects.all():
        to_create.append(TheoristDraftsConfiguration(theorist=theorist))
    TheoristDraftsConfiguration.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('theorist', '0007_alter_theorist_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoristDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=95, null=True)),
                (
                    'draft',
                    models.ImageField(
                        max_length=300,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='{app_label:.25}/{instance.theorist.full_name_slug}/drafts/{uuid:s}{ext}'
                        ),
                    ),
                ),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('is_public_available', models.BooleanField(default=False)),
                (
                    'theorist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='theorist.theorist'
                    ),
                ),
            ],
            options={
                'abstract': False,
                'ordering': ('-created_at',),
                'verbose_name': 'Theorist Draft',
                'verbose_name_plural': 'Theorist Drafts',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TheoristDraftsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public_available', models.BooleanField(default=True)),
                (
                    'theorist',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='drafts_configuration',
                        to='theorist.theorist',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Theorist Draft Configuration',
                'verbose_name_plural': 'Theorist Drafts Configurations',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunPython(generate_nested_theorist_configurations, reverse_code=migrations.RunPython.noop),
    ]
