# Generated by Django 5.1.7 on 2025-03-16 21:37

import django.contrib.postgres.fields
import django.utils.timezone
import django_lifecycle.mixins
import server.apps.carousel.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('button_text', models.CharField(max_length=100, blank=True)),
                ('button_url', models.URLField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'background_colors',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=server.apps.carousel.models.default_background_colors,
                        size=2,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
