# Generated by Django 5.1.7 on 2025-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
