# Generated by Django 5.1.11 on 2025-06-14 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('carousel', '0002_alter_carousel_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ('-pk',), 'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousels'},
        ),
    ]
