# Generated by Django 5.1.11 on 2025-07-10 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(35)], verbose_name='complaint text'
            ),
        ),
    ]
