# Generated by Django 4.2.7 on 2024-06-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                choices=[
                    ("JR", "Учень математики"),
                    ("OP", "Олімпіадник"),
                    ("TC", "Вчитель математики"),
                    ("GR", "Гуру математики"),
                    ("LD", "Володар математики"),
                ],
                default="JR",
                max_length=2,
                verbose_name="rank",
            ),
        ),
    ]
