# Generated by Django 5.0.6 on 2024-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="templates/static/profile_pics"
            ),
        ),
    ]
