# Generated by Django 5.0.10 on 2025-02-16 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_profileimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
